### ISSUE TITLE
idées habitant

### ISSUE THREAD

**Issue by pierromond** [nicolas-f/NoiseCaptureKotlin#13]
D. : "Est-ce que tu penses qu’il serait possible d’ajouter la possibilité pour l’utilisateur d’accéder à une ressource (sous forme de page ou de popup) lorsqu’il choisit une bande dans le spectre ? Dans cette page il pourrait retrouver des exemples d’objets et d’activités humaines qui produisent un bruit sur la porteuse correspondante à la bande sélectionnée."

**Comment by nicolas-f** [comment]
ne met pas les issues ici, le depot sera détruit avant la migration

**Comment by nicolas-f** [comment]
j'ai ajouté le tag noisecapture2 dans le depot officiel
